# 워크플로우의 이름
name: AI News Summarizer

# 언제 실행할지 결정
on:
  # 매일 아침 9시(UTC 기준 0시)에 자동으로 실행
  schedule:
    - cron: '0 0 * * *'
  # 수동으로도 실행할 수 있도록 버튼 추가
  workflow_dispatch:

jobs:
  summarize_news: # 작업의 역할을 명확하게 표현
    # 어떤 OS에서 실행할지 결정
    runs-on: ubuntu-latest

    steps:
      # 1. 내 코드를 GitHub 서버로 가져오기
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. 파이썬 환경 설정하기
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' # 우리가 사용한 파이썬 버전

      # 3. 의존성 캐싱으로 워크플로우 속도 향상
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          # requirements.txt 파일이 변경될 때만 캐시를 새로 생성
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4. 필요한 라이브러리 설치하기
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. 파이썬 스크립트 실행하기
      - name: Run Python script
        # GitHub Secrets에 저장된 키들을 환경 변수로 설정
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          NOTION_API_KEY: ${{ secrets.NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
          KAKAO_REFRESH_TOKEN: ${{ secrets.KAKAO_REFRESH_TOKEN }}
        run: python3 main.py